# -*- coding: utf-8 -*-
"""heart-doğan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUVwv-ff643LfPpmL2M5vSHR_0Nze5lm

Importing the Dependencies
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

"""Data Collection and Processing"""

# loading the cvs data to a Pandas DataFrame
heart_data = pd.read_csv('/content/data.csv')

# print first 5 rows of the dataset
heart_data.head()

# print last 5 rows of the dataset
heart_data.tail()

# number of rows and colums in the dataset
heart_data.shape

# getting some info about the data
heart_data.info()

# checking for missing values
heart_data.isnull().sum()

# statistical measures about the data
heart_data.describe()

# checking the distribution of Target Variable
heart_data['target'].value_counts()

"""1 --> Defective Heart 2 --> Healthy Heart

Splitting the Feature and Target
"""

x = heart_data.drop(columns='target', axis=1)
y = heart_data['target']

print(x)

print(y)

"""Splitting the Data into Trainig data and Test Data"""

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, stratify=y, random_state=2)

print(x.shape, x_train.shape, x_test.shape)

"""Model Training

Logistic Regression
"""

model = LogisticRegression()

# training the LogisticRegression model with Training data
model.fit(x_train, y_train)

"""Model Evaluation

Accuracy Score
"""

# accuracy on training data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

print('Accuracy on training data : ', training_data_accuracy)

# accuracy on test data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

print('Accuracy on test data : ', test_data_accuracy)

input_data = (41,0,1,130,204,0,0,172,0,1.4,2,0,2)

# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

!mkdir -p heart-disease-ml/src
!mkdir -p heart-disease-ml/models

!cp /content/*.ipynb heart-disease-ml/notebook.ipynb

# Commented out IPython magic to ensure Python compatibility.
# %%writefile heart-disease-ml/src/train.py
# import pandas as pd
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import StandardScaler
# from sklearn.ensemble import RandomForestClassifier
# import joblib
# 
# df = pd.read_csv("data/data.csv")
# 
# X = pd.get_dummies(df.drop("target", axis=1))
# y = df["target"]
# 
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# 
# scaler = StandardScaler()
# X_train_scaled = scaler.fit_transform(X_train)
# 
# model = RandomForestClassifier(n_estimators=100, random_state=42)
# model.fit(X_train_scaled, y_train)
# 
# joblib.dump(model, "../models/best_model.pkl")
# joblib.dump(scaler, "../models/scaler.pkl")
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile heart-disease-ml/src/predict.py
# import joblib
# import pandas as pd
# 
# def predict(input_dict):
#     model = joblib.load("../models/best_model.pkl")
#     scaler = joblib.load("../models/scaler.pkl")
# 
#     df = pd.DataFrame([input_dict])
#     df_scaled = scaler.transform(df)
# 
#     prob = model.predict_proba(df_scaled)[0][1]
#     return prob
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile heart-disease-ml/requirements.txt
# pandas
# numpy
# sklearn.model_selection
# sklearn.model_selection
# sklearn.model_selection
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile heart-disease-ml/.gitignore
# __pycache__/
# *.pkl
# *.csv
# .DS_Store
#

# Commented out IPython magic to ensure Python compatibility.
# %%writefile heart-disease-ml/README.md
# # Heart Disease ML Project
# 
# This project predicts heart disease using Logistic Regression, Random Forest, and XGBoost.
# 
# ## How to run
# 
# ```bash
# python src/train.py
#

!cp results_summary.csv heart-disease-ml/results_summary.csv
!cp best_model.pkl heart-disease-ml/models/best_model.pkl
!cp scaler.pkl heart-disease-ml/models/scaler.pkl

!tree heart-disease-ml

!pip install joblib

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(x_train, y_train)

import joblib

joblib.dump(model, "model.pkl")