# -*- coding: utf-8 -*-
"""Vize Ödev

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rqc9iXHEJBbsNWYx1uvccUX5hza-vDyl
"""

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# --- 1. Simüle edilmiş kan testi verileri ---
# 100 örnek × 5 özellik (ör: biyolojik ölçümler)
X = np.random.rand(100, 5)

# Sınıflar: 0 = A, 1 = B, 2 = AB, 3 = O
y = np.random.randint(0, 4, 100)

# --- 2. Eğitim / test seti ---
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# --- 3. Model oluştur ve eğit ---
model = RandomForestClassifier(n_estimators=50, random_state=42)
model.fit(X_train, y_train)

# --- 4. Test setinde tahmin ---
y_pred = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))

# --- 5. Görselleştirme (ilk iki özellik üzerinden) ---
plt.scatter(X_test[:, 0], X_test[:, 1], c=y_pred, cmap='viridis')
plt.title("Random Forest Kan Grubu Tahminleri (Test Seti)")
plt.xlabel("Özellik 1")
plt.ylabel("Özellik 2")
plt.colorbar(label='Tahmin Edilen Kan Grubu (0=A, 1=B, 2=AB, 3=O)')
plt.show()

import numpy as np
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# --- 1. Simüle edilmiş kan testi verileri ---
# 100 örnek × 5 özellik (kan testi ölçümleri)
X = np.random.rand(100, 5)

# --- 2. K-Means kümeleme ---
# 4 kan grubu olduğu için 4 küme
kmeans = KMeans(n_clusters=4, random_state=42)
labels = kmeans.fit_predict(X)

# --- 3. Görselleştirme (ilk iki özellik üzerinden) ---
plt.scatter(X[:, 0], X[:, 1], c=labels, cmap='viridis')
plt.title("K-Means Kümeleme: Kan Grubu Verisi")
plt.xlabel("Özellik 1")
plt.ylabel("Özellik 2")
plt.colorbar(label='Küme Numarası')
plt.show()

# --- 4. Küme merkezleri ---
print("Küme merkezleri (centroids):\n", kmeans.cluster_centers_)

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM
from tensorflow.keras.utils import to_categorical

# --- 1. Simüle edilmiş kan testi dizileri ---
# 100 örnek, 5 ölçüm (özellik sırası önemli)
X = np.random.rand(100, 5)

# Kan grubu etiketleri: 0=A, 1=B, 2=AB, 3=O
y = np.random.randint(0, 4, 100)
y_cat = to_categorical(y, num_classes=4)  # One-hot encoding

# --- 2. LSTM girişine uygun hâle getirme ---
# [samples, timesteps, features]
X = X.reshape((X.shape[0], X.shape[1], 1))

# --- 3. Model oluştur ---
model = Sequential([
    LSTM(16, input_shape=(X.shape[1], 1)),
    Dense(16, activation='relu'),
    Dense(4, activation='softmax')  # 4 kan grubu
])

# --- 4. Modeli derle ---
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# --- 5. Modeli eğit ---
model.fit(X, y_cat, epochs=30, batch_size=8, verbose=1)

# --- 6. Tahmin ---
sample_idx = 0
sample = X[sample_idx:sample_idx+1]
pred = model.predict(sample)
predicted_group = np.argmax(pred)
print(f"Örnek {sample_idx} için tahmin edilen kan grubu: {predicted_group} (0=A, 1=B, 2=AB, 3=O)")
print(f"Gerçek kan grubu: {y[sample_idx]}")

import pandas as pd
from sklearn.linear_model import LinearRegression

# --- 1. Simüle edilmiş veri ---
data = {
    "age": [25, 40, 35, 50, 30],                # yaş
    "weight": [60, 80, 70, 90, 65],             # kilo (kg)
    "BMI": [22, 27, 24, 30, 23],                # vücut kitle indeksi
    "post_meal_glucose": [120, 150, 130, 160, 125],  # öğün sonrası glukoz
    "activity_level": [3, 1, 2, 1, 3],          # fiziksel aktivite 1-3 arası
    "fasting_glucose": [90, 110, 95, 120, 92]   # hedef: açlık kan şekeri
}

df = pd.DataFrame(data)

# --- 2. Özellikler ve hedef ---
X = df[["age", "weight", "BMI", "post_meal_glucose", "activity_level"]]
y = df["fasting_glucose"]

# --- 3. Model oluştur ve eğit ---
model = LinearRegression().fit(X, y)

# --- 4. Katsayıları ve tahmini yazdır ---
print("Coefficients:", model.coef_)

# Örnek bir kişinin tahmini kan şekeri
sample = [[45, 75, 26, 140, 2]]  # yaş, kilo, BMI, öğün sonrası glukoz, aktivite
predicted_glucose = model.predict(sample)[0]
print(f"Tahmini açlık kan şekeri: {predicted_glucose:.2f} mg/dL")

import numpy as np
from sklearn.svm import SVC

# --- 1. Simüle edilmiş moleküler özellikler ---
# 50 örnek, 5 özellik (ör: moleküler ağırlık, logP, hidrofobiklik, polarite, yük)
X = np.random.rand(50, 5)

# 0 = non-toxic, 1 = toxic
y = np.random.randint(0, 2, 50)

# --- 2. SVM sınıflandırma modeli ---
model = SVC(kernel='rbf', probability=True, random_state=42)
model.fit(X, y)

# --- 3. Yeni bir bileşik tahmini ---
new_compound = np.random.rand(1, 5)
prob = model.predict_proba(new_compound)[0, 1]

prediction = model.predict(new_compound)[0]
print(f"Tahmin edilen sınıf: {prediction} (0=non-toxic, 1=toxic)")
print(f"Tahmin edilen toksisite olasılığı: {prob:.2f}")